runtime: python
api_version: 1
application: europython2010
version: 1
handlers:
- url: /jqtouch
  static_dir: jqtouch/jqtouch
- url: /themes
  static_dir: jqtouch/themes
- url: /a
  static_dir: icodemash
- url: /services/.*
  script: services.py
  login: admin
- url: /.*
  script: ae_timetable.py    